services:
  binfmt:
    image: multiarch/qemu-user-static:register
    privileged: true
    platform: linux/amd64
    command: ["--reset", "-y", "--capability", "yes"]

  builder:
    build:
      context: .
      dockerfile: Dockerfile
    image: alpine-milkv-builder:latest
    depends_on:
      - binfmt
    privileged: true
    volumes:
      - ./images:/project/images
      - kernel-src:/project/kernel/linux
    working_dir: /project

  shell:
    extends: builder
    stdin_open: true
    tty: true
    entrypoint: /bin/bash

volumes:
  kernel-src:
